Stas service
KabanovvonabaK/java-explore-with-me pull request #3
Opened 2023-07-02 16:30 UTC by KabanovvonabaK

2023-07-03 20:15 UTC, Donald522 requested changes
Привет!

Все хорошо, оставил пару замечаний

2023-07-03 20:15 UTC, Donald522 commented on docker-compose.yml
> +#    depends_on:
Закомменченный код нужно удалить

2023-07-03 20:15 UTC, Donald522 commented on stats-service/stats-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    @Query("select new ru.practicum.StatsDto(h.app, h.uri, count(distinct h.ip) as hits) " +
Не очень хорошо, что репозиторий возвращает dto модель

2023-07-03 20:15 UTC, Donald522 commented on stats-service/stats-server/src/main/resources/schema.sql
> +    URI VARCHAR(50) NOT NULL,
на uri и timestamp надо добавить индексы

2023-07-05 17:50 UTC, KabanovvonabaK commented on docker-compose.yml
> +#    depends_on:
Удалил.

2023-07-05 17:50 UTC, KabanovvonabaK commented on stats-service/stats-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    @Query("select new ru.practicum.StatsDto(h.app, h.uri, count(distinct h.ip) as hits) " +
Поправил.

2023-07-05 17:50 UTC, KabanovvonabaK commented on stats-service/stats-server/src/main/resources/schema.sql
> +    URI VARCHAR(50) NOT NULL,
Добавил.

2023-07-06 19:29 UTC, Donald522 approved these changes

2023-07-08 10:43 UTC, merged