Feature Comments
KabanovvonabaK/java-explore-with-me pull request #5
Opened 2023-07-17 10:09 UTC by KabanovvonabaK

2023-07-17 21:28 UTC, Donald522 requested changes
Привет!

Написал замечания.

Вопрос про тесты - не увидел ни одного. Мне кажется что их стоит написать.

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentAdminController.java
> +    public void delete(@PositiveOrZero @PathVariable int comId) {
Может быть полезно передавать сюда также такие вещи
 - кто удалил
 - причина удаления

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +public class CommentUserController {
Комменты могут добавлять неавторизованные пользователи тоже?
Думаю имеет смысл разделить на публичный и приватный апи

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +    public CommentForView findByIdForUser(@Positive @PathVariable("userId") int userId,
Как используется этот метод?

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/dto/CommentEvent.java
> +public class CommentEvent {
Название класса не соответствует сути

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +    public CommentForView add(@Positive @PathVariable("userId") int userId,
Почему такой путь?
Мы же не создаем тут нового пользователя, а комментарий добавляем

Ну и userId соответственно не стоит через pathVar передавать. Лучше через заголовок

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            } else {
Этот else ведь к другому if

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            if (eventFromDb.getInitiator().getId().equals(userId)) {
Комментировать только свои события можно?
Что делает эта проверка?

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +                throw new ConflictException("Impossible to create comment to unpublished event");
Это не кофликт

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            } else {
Тоже самое, else к другому if относится

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        checkAuthorCommentOrThrow(userId, commentFromDb);
Проверку userId надо делать в базе, условие к запросу

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        Comment commentFromDb = getCommentOrThrow(comId);
Зачем делать select перед удалением?

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            throw new DateTimeException("Impossible to update comment after 2 hours after publishing");
Такие вещи не стоит хардкодить
Либо убираем эту логику, либо 2 часа выносим в конфиг

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        checkAuthorCommentOrThrow(userId, commentFromDb);
Эту проверку тоже в запрос

2023-07-17 21:28 UTC, Donald522 commented on ewm-service/src/main/resources/schema.sql
> +    EVENT_ID   BIGINT                                  NOT NULL,
На eventId нужен индекс

2023-07-18 06:22 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +public class CommentUserController {
>Комменты могут добавлять неавторизованные пользователи тоже?
Нет, для этого в add() мы ловим userId.
Но вот просматривать комменты могут действительно неавторизированные пользователи - разделил пользовательский контроллер на приватный и публичный и унёс в публичный просмотр всех комментов.

2023-07-18 06:43 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +    public CommentForView findByIdForUser(@Positive @PathVariable("userId") int userId,
Сам фигню написал. Отказался от связки comId и userId, вынес метод в публичный контроллер и теперь просто тяну комментарий по его id.

2023-07-18 06:46 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/dto/CommentEvent.java
> +public class CommentEvent {
Остался как часть нереализованной логики - выпилил.

2023-07-18 07:10 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/controler/CommentUserController.java
> +    public CommentForView add(@Positive @PathVariable("userId") int userId,
Согласен. Для добавления коммента теперь путь просто /comments, userId ловим в как хэдэр.
Тесты апнул.

2023-07-18 07:19 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            } else {
Поправил else, провел небольшой рефакторинг.

2023-07-18 07:23 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            if (eventFromDb.getInitiator().getId().equals(userId)) {
>Комментировать только свои события можно?

Нет.

>Что делает эта проверка? 

Это лефтовер от первой задумки - особая логика при комментировании автором события. Решил не пилить, так как дедлайн уже близко, а я уже задолбался.
Выпилил.

2023-07-18 07:34 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +                throw new ConflictException("Impossible to create comment to unpublished event");
Пробросил собственный эксепшен.

2023-07-18 07:36 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            } else {
Изменил логику в методе.

2023-07-18 07:40 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            throw new DateTimeException("Impossible to update comment after 2 hours after publishing");
Убрал.

2023-07-18 07:41 UTC, KabanovvonabaK commented on ewm-service/src/main/resources/schema.sql
> +    EVENT_ID   BIGINT                                  NOT NULL,
Добавил.

2023-07-18 10:44 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        checkAuthorCommentOrThrow(userId, commentFromDb);
Не получилось сделать красиво, попробовал jpa и @query
С твоего позволения оставлю так.

2023-07-18 10:44 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        checkAuthorCommentOrThrow(userId, commentFromDb);
Не получилось сделать красиво, попробовал jpa и @query
С твоего позволения оставлю так.

2023-07-18 10:44 UTC, KabanovvonabaK commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        Comment commentFromDb = getCommentOrThrow(comId);
Что бы проверить что пользователь и есть автор.

2023-07-18 19:54 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        checkAuthorCommentOrThrow(userId, commentFromDb);
JPA не панацея. Если фремворк мешает писать код - надо отказаться от фреймворка.
Имхо, нет ничего лучше простого sql и jdbcTemplate. JPA это лишнее.

2023-07-18 19:55 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        Comment commentFromDb = getCommentOrThrow(comId);
Это надо делать в запросе:
```
delete from ...
where userId = ...
```

2023-07-18 20:00 UTC, Donald522 commented
> 



> > Привет!
> > Написал замечания.
> > Вопрос про тесты - не увидел ни одного. Мне кажется что их стоит написать.
> 
> Привет. Спасибо за ревью! По требованиям диплома - должны быть тесты для постмана на фичу, юнит и интеграционные это дополнительное задание со звёздочкой по желанию. Так как тесты занимают много времени, я сознательно не стал их пилить. В целом, я согласен что они должны быть.

Привет. Тут дело твое, я заставлять не буду.
Но дам совет, тк ты заканчиваешь курс и наверняка либо уже в поиске, либо будешь искать работу. Обращай внимание, пишут ли в команде, куда пойдешь, тесты. Спрашивай это на собесе. Это очень простой способ определить места, куда точно не стоит идти. Без тестов сколько угодно серьезная промышленная разработка невозможна. Часто написание тестов занимает больше времени, чем написание самой логики.

2023-07-18 20:01 UTC, Donald522 approved these changes

2023-07-19 07:03 UTC, merged